export VLLM_SKIP_WARMUP=true
export LLM_MODEL_ID=google/gemma-3-27b-it
export HF_TOKEN=xxx
export PT_HPUGRAPH_DISABLE_TENSOR_CACHE=false
export DATA_PATH=~/data
export MAX_TOTAL_TOKENS=500
export VLLM_USE_V1=0
export PT_HPU_LAZY_MODE=1
export VLLM_FP32_SOFTMAX=1
export VLLM_PROMPT_USE_FUSEDSDPA=False
#python vllm-gemma3-offline.py

#export VLLM_PROMPT_USE_FUSEDSDPA=False


#export VLLM_PROMPT_BS_BUCKET_MIN=1
#export VLLM_PROMPT_BS_BUCKET_STEP=1
#export VLLM_PROMPT_BS_BUCKET_MAX=1
#export VLLM_DECODE_BS_BUCKET_MIN=1
#export VLLM_DECODE_BS_BUCKET_STEP=1
#export VLLM_DECODE_BS_BUCKET_MAX=1
 
#export VLLM_PROMPT_SEQ_BUCKET_MIN=128
#export VLLM_PROMPT_SEQ_BUCKET_STEP=512
#export VLLM_PROMPT_SEQ_BUCKET_MAX=2048
#export VLLM_DECODE_BLOCK_BUCKET_MIN=128
#export VLLM_DECODE_BLOCK_BUCKET_STEP=128
#export VLLM_DECODE_BLOCK_BUCKET_MAX=2048


python gemma3.py 5
