# Parameterize base image components
ARG DOCKER_URL=vault.habana.ai/gaudi-docker
ARG VERSION=1.21.1
ARG BASE_NAME=ubuntu22.04
ARG PT_VERSION=2.6.0
ARG REVISION=latest
ARG REPO_TYPE=habanalabs

FROM ${DOCKER_URL}/${VERSION}/${BASE_NAME}/${REPO_TYPE}/pytorch-installer-${PT_VERSION}:${REVISION}

# Parameterize commit/branch for vllm-fork checkout
ARG VLLM_FORK_COMMIT=v0.7.2+Gaudi-1.21.0

ENV OMPI_MCA_btl_vader_single_copy_mechanism=none

RUN apt update && \
    apt install -y gettext moreutils jq && \
    ln -sf /usr/bin/python3 /usr/bin/python
WORKDIR /root

# Clone the vllm-fork repository
RUN git clone https://github.com/HabanaAI/vllm-fork.git && \
    cd vllm-fork && \
    git fetch -t && \
    git checkout ${VLLM_FORK_COMMIT}

# Install vllm-fork inside the container
ENV VLLM_TARGET_DEVICE=hpu
RUN cd vllm-fork && \
    pip install -v -e .

# Install additional Python packages
RUN pip install datasets && \
    pip install pandas

# Copy utility scripts and configuration
RUN mkdir -p /root/scripts/settings/
COPY entrypoint.py vllm_autocalc.py vllm_autocalc_rules.py /root/scripts/
COPY settings/settings_vllm.csv settings/defaults.yaml settings/varlist_conf.yaml settings/template_vllm_server.sh /root/scripts/settings/
WORKDIR /root/scripts

# Set entrypoint script
ENTRYPOINT ["python3", "/root/scripts/entrypoint.py"]
