declare -A ROLE_HOST
declare -A ROLE_IP
USR_P_NUM_INSTANCE=1
USR_D_NUM_INSTANCE=1
ROLE_HOST[P0]="skyriver01"; ROLE_IP[P0]="10.239.44.122"
ROLE_HOST[D0]="skyriver02"; ROLE_IP[D0]="10.239.44.130"
USR_DECODE_TP_SIZE=1
USR_DECODE_EP_SIZE=16
USR_CARDS_PER_NODE=16
USR_PREFILL_TP_SIZE=8
USR_PREFILL_EP_SIZE=8
USR_DECODE_NEED_SCALEOUT=0
USR_PREFILL_NEED_SCALEOUT=0
USR_PREFILL_USE_RAY=0
USR_PLATFORM_TYPE="SKYRIVERV3"
USR_QUANT_CONFIG_DECODE=inc_fp8_tp1ep16.json
USR_QUANT_CONFIG_PREFILL=inc_fp8_tp8ep8.json
USR_ETCD_META_SERVER=${USR_ETCD_META_SERVER:-${ROLE_IP[P0]}:2379}
USR_MOONCAKE_SERVER=${USR_MOONCAKE_SERVER:-${ROLE_IP[P0]}:50001}
USR_MOONCAKE_LOCAL_ADDR_PREFIX="10.239"
