# test_config.yaml
steps:
  - name: test_suite_g1
    flavor: g1
    command: hl-smi
  - name: test_suite_g2
    flavor: g2
    command: hl-smi
  - name: test_suite_g3
    flavor: g3
    command: hl-smi
