# test_config.yaml
steps:
  - name: Test Suite 1
    command: echo "Hello world 1!"
  - name: Test Suite 2
    command: echo "Hello world 2!"
  - name: Test Suite 3
    command: echo "Hello world 3!"
