model_name: "/root/software/data/pytorch/huggingface/hub/models--Qwen--Qwen2.5-VL-7B-Instruct/snapshots/cc594898137f460bfe9f0759e9844b3ce807cfb5/"
dtype: "bfloat16"
max_model_len: 32768
max_num_seqs: 32
num_prompts: 4
