name: deprecation-mssg-pr

on:
  pull_request:
    branches:
      - habana_main

jobs:
  close-pr:
    steps:
    - run: gh pr close ${{ github.event.number }} --comment "Starting from v1.23.0, the vLLM fork will reach end-of-life (EOL) and be deprecated in v1.24.0, remaining functional only for legacy use cases until then. At the same time, the vllm-gaudi plugin will be production-ready in v1.23.0 and will become the default by v1.24.0. This plugin integrates Intel Gaudi with vLLM for optimized LLM inference and is intended for future deployments. We strongly suggest preparing a migration path toward the plugin version: https://github.com/vllm-project/vllm-gaudi."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
